### ISSUE TITLE
Sotkanet connection not working

### ISSUE THREAD

**Issue by arhot** [rOpenGov/sotkanet#1]
Retrieving indicators has stopped working since early September. Below is the error message for the tutorial example. I tried both release and developer versions. I asked the persons responsible for the API at THL and they said they have been changed from http to https and guessed that might be the issue, the API is up and running anyway.

> dat <- GetDataSotkanet(indicators = 10013, years = 1990:2012, 
> -                        genders = c('female', 'male', 'total'), 
> -                        region.category = "EUROOPPA", 
> -                        region = "Suomi")
>   Retrieving indicator 10013
>   Error in `[.data.frame`(SotkanetIndicators(indicator), , c("indicator",  : 
>   undefined columns selected
>   In addition: Warning messages:
>   1: In sotkanet.json_query(url) :
>   Sotkanet URL https://www.sotkanet.fi/rest/1.1/indicators does not exist - returning NULL!
>   2: In sotkanet.json_query(url) :
>   Sotkanet URL https://www.sotkanet.fi/rest/1.1/indicators/10013 does not exist - returning NULL!

**Comment by antagomir** [comment]
Tnx for report! It works now again after changing the base url to http. I have also submitted an update to CRAN but this comes with delay. For immediate access to the up-to-date version you can install the latest one from github with (in R): library(devtools); devtools::install_github("ropengov/sotkanet")
