### ISSUE TITLE
Sotkanet siirtyy käyttämään Tilastokeskuksen virallisia hyvinvointialueiden aluekoodeja

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/sotkanet#11]
Sotkanet on siirtynyt käyttämään Tilastokeskuksen virallisia hyvinvointialueiden aluekoodeja. 

Sotkanetissä on ollut käytössä epäviralliset hyvinvointialueiden aluekoodit, jotka otettiin käyttöön maaliskuussa 2021, jolloin virallisia koodeja ei ollut vielä käytettävissä.
[Hyvinvointialueet sekä Helsingin kaupunki ja Ahvenanmaa 2023 (Tilastokeskus)](https://www.stat.fi/fi/luokitukset/hyvinvointialue/)

Tämä vaikuttaa rajapinnoissa aluekoodeihin id sekä code-arvoihin. 

THL:n Sotkanet-tiimi on toimittanut koodimuutoksen 23.1.2023. 

Liitin tämän tiedostoon:
`inst/extdata/sotkanet_hyvinvointialueet.csv`

TODO:
- muuta koodi käyttämään tätä versiota
- lisää dokumentaatioon maininta taulukon lähteestä (THL:n Sotkanet-tiimi to antagomir 23.1.2023)
- päivitä paketti CRANiin

**Comment by pitkant** [comment]
Hyvinvointialueiden koodit tulevat suoraan APIsta, oliko tässä paketissa jotain mukana olevia datasettejä mitkä tarvitsisivat erikseen päivittämistä?
